### ISSUE TITLE
Couldn't connect to sysmodule

### ISSUE THREAD

**Issue by Kemetric** [tallbl0nde/TriPlayer#35]
I'm simply not able to connect to the sysmodule. Here's a photo:

https://cdn.discordapp.com/attachments/697991307292966914/790009337409306664/2020121917284000-DB1426D1DFD034027CECDE9C2DD914B8.jpg

**Comment by tallbl0nde** [comment]
Could you upload the logs please? Both `/switch/TriPlayer/application.log` and `/switch/TriPlayer/sysmodule.log` would be perfect. What firmware version + CFW are you running also?

**Comment by tallbl0nde** [comment]
Closing this as there's been no reply for nearly a month - please reopen if you wish to follow it up.

**Comment by wvandolen** [comment]
Heyyy!! I'm having the same issue. If anyone's there, I would love to talk. Thanks!!
