### ISSUE TITLE
12.0.0 Crashing Issue

### ISSUE THREAD

**Issue by Quaashie** [tallbl0nde/TriPlayer#40]
When opening the TriPlayer from the Homebrew Menu, it will give a crash report and not launch. This only happened after updating the switch firmware from 11.0.1 to 12.0.0. I've added a screenshot from the crash to show.
![report](https://user-images.githubusercontent.com/82472895/114612525-dbe95a80-9c67-11eb-919d-0134f8b79f90.PNG)

**Comment by tallbl0nde** [comment]
Thanks for reporting this, I was hoping there wouldn't be any issues as I don't use "atmosphere extensions". I'll give it a look eventually but im hoping it's just a matter of compiling with the latest libnx, as I can see they've made some changes regarding IPC.

**Comment by yyoossk** [comment]
TriPlayer is greatest app
I was translate japanese
When will it upgrade?

**Comment by tallbl0nde** [comment]
@yyoossk I started working on it before Christmas, the main issue was I didn't have a way to automatically scale text (I believe it was Japanese where it would overflow some areas). I spent a few weeks redoing my ui library to allow for this, and since then have have busy with work and uni, leaving me with almost no desire to code when I get home since I've been doing it all day. One day I'll release an update!

Regarding 12.0.0 though, I'm hoping it's just a matter of recompiling with libnx. If so, a quick fix will probably be out before the translation side of things. If not, it could take a while longer.

**Comment by yyoossk** [comment]
thx!

**Comment by TheSniperFox** [comment]
Same problem here too.
Any updates so far about this issue?

**Comment by tallbl0nde** [comment]
I'm quite busy with work and uni and other personal things so no ETA. I'll get to it eventually.

If a developer reads this - if you could try compiling the `libnx-update` branch against the latest libnx (as in compile that from GitHub), perhaps that should fix it.

**Comment by tallbl0nde** [comment]
Little update: I tried compiling with the very latest libnx commits and while the sysmodule compiles, the application doesn't. It uses SDL which hasn't been updated properly for the 4.0.0 HID changes, which seem to be removed entirely in libnx for the next version. Looks like we'll have to wait for them to properly update all the libraries, so 12.0.0 won't be supported for a little while.

**Comment by TheSniperFox** [comment]
> Little update: I tried compiling with the very latest libnx commits and while the sysmodule compiles, the application doesn't. It uses SDL which hasn't been updated properly for the 4.0.0 HID changes, which seem to be removed entirely in libnx for the next version. Looks like we'll have to wait for them to properly update all the libraries, so 12.0.0 won't be supported for a little while.

Ok. thank you for trying and letting us know what's going on.

**Comment by SkullMP** [comment]
I hope this could get fixed soon. Glad I am not the only one that had this issue.

**Comment by TheSniperFox** [comment]
> I hope this could get fixed soon. Glad I am not the only one that had this issue.

yea same. I hope he updates it soon its too good of an app to leave behind. 

it was my main reason i play racing games again on the switch so i can playback eurobeat whenever i play them like i did with the PSP

**Comment by Theguysayhi** [comment]
Hope progress is going well. Looking forward to the update fix!

**Comment by pixeltester** [comment]
> 
> 
> Little update: I tried compiling with the very latest libnx commits and while the sysmodule compiles, the application doesn't. It uses SDL which hasn't been updated properly for the 4.0.0 HID changes, which seem to be removed entirely in libnx for the next version. Looks like we'll have to wait for them to properly update all the libraries, so 12.0.0 won't be supported for a little while.

Just in case you didn't see it, it was all updated 10 days ago with SDL included.

**Comment by tallbl0nde** [comment]
I did, and as of tomorrow I'll be on my month long break... hopefully I can get an update out in this time 😉

**Comment by SeongGino** [comment]
Unfortunately from my environment, libtesla seems to be getting in the way of compilation. A bunch of errors spitting out almost exclusively from it.
Hoping to see a fix soon. (^^;

**Comment by Smoker1** [comment]
This is also crashing on 12.0.2. I try to run the NSP, and it can not run it. Get kicked back to the Home Screen.

**Comment by tallbl0nde** [comment]
I've fixed this a couple days ago on the `dev` branch - if you know what you're doing you can compile and use that, otherwise I'm hoping to release an update for 12.0.0 soon!

**Comment by aocodes** [comment]
I've successfully compiled the latest dev changes, other than missing (asian?) fonts on the tesla menu it works great for me on the latest fw and atmosphere!

**Comment by Bur0ri** [comment]
> I've successfully compiled the latest dev changes, other than missing (asian?) fonts on the tesla menu it works great for me on the latest fw and atmosphere!

Mind sharing for the folks who can't compile? 👀

**Comment by aocodes** [comment]
> 
> 
> > I've successfully compiled the latest dev changes, other than missing (asian?) fonts on the tesla menu it works great for me on the latest fw and atmosphere!
> 
> Mind sharing for the folks who can't compile? 👀

As @SeongGino elaborated on libtesla compilation errors, all I had to do was download the latest libtesla and paste it in overlay/libs folders. The one that's linked to the source was outdated.

**Comment by Bur0ri** [comment]
> > > I've successfully compiled the latest dev changes, other than missing (asian?) fonts on the tesla menu it works great for me on the latest fw and atmosphere!
> > 
> > 
> > Mind sharing for the folks who can't compile? 👀
> 
> As @SeongGino elaborated on libtesla compilation errors, all I had to do was download the latest libtesla and paste it in overlay/libs folders. The one that's linked to the source was outdated or something.

Ah I meant the actual compiled app for your Switch

**Comment by aocodes** [comment]
Oh that's what you meant ahaha. But I'm a little hesitant cause I'm not sure if I'm allowed to post here.

**Comment by tallbl0nde** [comment]
The 12.0.0 support update has been released, sorry it took so long! :)

**Comment by Gokou-Ruri** [comment]
> The 12.0.0 support update has been released, sorry it took so long! :)

Hello! It's having the same problem now on 16.0.1, can you fix it?

**Comment by DirkBraakman** [comment]
> > The 12.0.0 support update has been released, sorry it took so long! :)
> 
> Hello! It's having the same problem now on 16.0.1, can you fix it?

Same here. A fix would be great!
