### ISSUE TITLE
Firmware 13.0 UPDATE REQUIRED

### ISSUE THREAD

**Issue by AMGe350** [tallbl0nde/TriPlayer#46]
Hey buddy, when do you think you might get around to updating Triplayer to be compatible with Nintys latest release Firmware 13?

**Comment by tallbl0nde** [comment]
It works perfectly on 13.0.0 for me, are you using the latest Atmosphere?

**Comment by AMGe350** [comment]
My friend, thankyou for your kind response. I deleted the app & reinstalled & hey presto, we were up & running. Just for information, before I reinstalled after updating to 13.0 firmware, the error message was, can't get the sysmodule to open!!

Samsung Z Fold 2 512GB
________________________________

**Comment by tallbl0nde** [comment]
Glad to hear, there must have been a problem with the sysmodule then. Enjoy :)
