### ISSUE TITLE
Non ASCII glitch Fix

### ISSUE THREAD

**Issue by trextaco9** [tallbl0nde/TriPlayer#56]
I was just wondering if you got the time, would you ever attempt to fix the glitch where triplayer can't get past the "preparing your library" screen when you have files with non ASCII characters? The rename.bat doesn't seem to be working for me and I can't seem to find any files with odd characters.

**Comment by Everynevah** [comment]
yes, definitely something is not working properly with the bat file,
or maybe triplayer it self should be able to read any file names, regardless of ascii, i mean, thats what any music player does.
Lets hope this gets fixed soon, as of now i tried to use the bat, then manually remove some files that it created with some japanese/chinese types (i dont know why the batfile did this) but got no positive results, there's plenty of characters in here, so who knows if i missed anything.
Fixing Triplayer would be easier, maybe?
anyhow, thanks to the devs, your work is amazing!

**Comment by tallbl0nde** [comment]
It's a common issue shared between all homebrew, so it can't be fixed (nor do I have the time anymore).

**Comment by DraconicNEO** [comment]
> It's a common issue shared between all homebrew, so it can't be fixed (nor do I have the time anymore).

if you don't have time to work on the project you should archive the repository or leave a notice in the readme that says this app isn't being maintained anymore.

Otherwise people are going to expect patches and updates since they haven't exactly been told otherwise.
